# Generated by Django 4.2.7 on 2026-05-30 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0005_remove_detectionevent_device_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("KNOWN", "Known Person"),
                            ("UNKNOWN", "Unknown Person"),
                            ("INTRUDER", "Intruder"),
                            ("VEHICLE", "Vehicle"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="devices.device",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="homes.home",
                    ),
                ),
                (
                    "matched_face",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="devices.faceprofile",
                    ),
                ),
                (
                    "matched_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_events",
                        to="homes.homemember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("event_type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
