# Generated by Django 4.2.7 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionevent",
            name="camera_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="snapshot_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
