# Generated by Django 4.2.7 on 2026-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_detectionevent_camera_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detectionevent",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="event_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PERSON_DETECTED", "Person Detected"),
                    ("DOOR_UNLOCKED", "Door Unlocked"),
                    ("DOOR_LOCKED", "Door Locked"),
                    ("MOTION_DETECTED", "Motion Detected"),
                    ("VEHICLE_DETECTED", "Vehicle Detected"),
                ],
                default="PERSON_DETECTED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="person_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="detectionevent",
            index=models.Index(
                fields=["timestamp"], name="events_dete_timesta_4acd90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionevent",
            index=models.Index(
                fields=["person_type"], name="events_dete_person__0610f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionevent",
            index=models.Index(
                fields=["event_type"], name="events_dete_event_t_3f1e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionevent",
            index=models.Index(
                fields=["camera_location"], name="events_dete_camera__807e8b_idx"
            ),
        ),
    ]
