# Generated by Django 4.2.7 on 2026-05-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0001_initial"),
        ("devices", "0003_faceprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faceprofile",
            name="home",
        ),
        migrations.RemoveField(
            model_name="faceprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="faceprofile",
            name="home_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_profiles",
                to="homes.homemember",
            ),
        ),
    ]
