# Generated by Django 4.2.7 on 2026-05-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0001_initial"),
        ("devices", "0004_remove_faceprofile_home_remove_faceprofile_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionevent",
            name="device",
        ),
        migrations.RemoveField(
            model_name="detectionevent",
            name="home",
        ),
        migrations.RemoveField(
            model_name="detectionevent",
            name="matched_user",
        ),
        migrations.AddField(
            model_name="smartlock",
            name="last_unlocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("camera", "CAMERA"),
                    ("smart_lock", "SMART_LOCK"),
                    ("sensor", "SENSOR"),
                    ("alarm", "ALARM"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="smartlock",
            name="last_unlocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlock_events",
                to="homes.homemember",
            ),
        ),
        migrations.DeleteModel(
            name="AccessLog",
        ),
        migrations.DeleteModel(
            name="DetectionEvent",
        ),
    ]
