# Generated by Django 4.2.7 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_remove_detectionevent_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="stream_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
